/* Auto-generated by genmsg_cpp for file /home/johanv/code/vertensj-quadrotor/Controller_Core2/msg/waypoint.msg */
#ifndef CONTROLLER_CORE2_MESSAGE_WAYPOINT_H
#define CONTROLLER_CORE2_MESSAGE_WAYPOINT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Controller_Core2
{
template <class ContainerAllocator>
struct waypoint_ {
  typedef waypoint_<ContainerAllocator> Type;

  waypoint_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , yaw(0.0)
  {
  }

  waypoint_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  , yaw(0.0)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _z_type;
  float z;

  typedef float _yaw_type;
  float yaw;


  typedef boost::shared_ptr< ::Controller_Core2::waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Controller_Core2::waypoint_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct waypoint
typedef  ::Controller_Core2::waypoint_<std::allocator<void> > waypoint;

typedef boost::shared_ptr< ::Controller_Core2::waypoint> waypointPtr;
typedef boost::shared_ptr< ::Controller_Core2::waypoint const> waypointConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Controller_Core2::waypoint_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Controller_Core2::waypoint_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Controller_Core2

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Controller_Core2::waypoint_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Controller_Core2::waypoint_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Controller_Core2::waypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "b81376c2774ff4f956e5110e01c9db26";
  }

  static const char* value(const  ::Controller_Core2::waypoint_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xb81376c2774ff4f9ULL;
  static const uint64_t static_value2 = 0x56e5110e01c9db26ULL;
};

template<class ContainerAllocator>
struct DataType< ::Controller_Core2::waypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Controller_Core2/waypoint";
  }

  static const char* value(const  ::Controller_Core2::waypoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Controller_Core2::waypoint_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
float32 yaw\n\
\n\
\n\
";
  }

  static const char* value(const  ::Controller_Core2::waypoint_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::Controller_Core2::waypoint_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Controller_Core2::waypoint_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
    stream.next(m.yaw);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct waypoint_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Controller_Core2::waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Controller_Core2::waypoint_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_CORE2_MESSAGE_WAYPOINT_H

